<?php

$info = <<<INFO
<p>
	The system is based on 4 x <a href='http://www.jenconsusa.com/2-Cryogenics/30-Vapor-Phase-Cryostorage/Taylor-Wharton-LABS-80K-Vapor-Phase-Cryostorage.html'>LABS-80K</a>
	and 1 x <a href='http://www.jenconsusa.com/2-Cryogenics/6-Refrigerators/35-Taylor-Wharton-LS/Taylor-Wharton-LS4800-Cryogenic-Refrigerator.html'>LS4800</a> cryogenic refrigerators from Jencons. 
	Monitoring and filling is through M505 controllers by <a href='http://www.mowden.co.uk/'>Mowden Controls</a>. Data from  the controllers is logged onto a MySQL database, made available over the web and watched for errors by custom Perl scripts running under <a href='http://www.ubuntu.com/'>ubuntu</a> on an ancient P4 PC called out of retirement.
</p>

  

<p>
	The bulk tank pressure is determined by a pair of <a href='http://www.roxspur.com/pressure/hps.php'>HPS sensors from Roxpur</a>, connected to a 
	<a href='http://labjack.com/u6'>Labjack U6 analogue - digital converter</a>. 
	Bulk tank contents is calculated from the pressure difference between the top and bottom of the tank.
	Room oxygen monitoring is by systems from 
	<a href='http://quantumproduction.co.uk/gallery8.htm'>Quantum</a>, and logged onto the database via a labjack ADC channel.   
	The labjack also detects the state of the emergency shutoff valve by means of a reed switch across a digital i/o channel. 
    A <a href='http://labjack.com/catalog/ei1034-temperature-probe'>temperature probe</a> attached to the plumbing detects LN2 
	flow in the external fill point, also via the labjack, and thus logs the time over which the pipe is in use.	
	
</p>
<p>
	LN2 is generated by a <a href='http://www.stirlingcryogenics.com/products/stirlin-liquid-nitrogen-plants/all/stirlin-1/'>StrirLIN-1</a> plant from 
	<a href='http://www.stirlingcryogenics.com'>Stirling cryogenics</a> producing up to 250 litres/day.   
	Currently we only log 'running/not running' on the database and display the basic statistics on the web.
    This is determined via a 24V source which is present when the plant is running,
    this is converted to logic via an optoisolator and the state is read by the labjack.
</p>

<p>
	All of these suppliers - with the spectacular exception of Quantum - have been very helpful and have provided excellent support for their equipment.
</p>

<p>
	The primary Perl script interrogates each refrigerators approximately every 4 seconds.  
	The labjack inputs are continually monitored by a separate python script. 
	Both scripts log data every 30 minutes, unless there is a change in any condition, in which case data is logged immediately.
	A perl script watches the database and raises email and SMS alerts in case of problems.
</p>

<p>
		At the same time, images are grabbed from 2 of 3 (depending on the event) <a href='http://www.axis.com/products/cam_m1031w/'>Axis M1031 ip cameras</a>.
</p>

<p>
	Samples are entirely in vapour phase nitrogen. The periodic spikes in temperature are caused by
	liquid nitrogen fills which boil off vapour and lower the temperature seen by the upper sensor by approximately 10C. 
	Fills are synchronised between tanks to reduce liquid nitrogen consumption. 
	The shorter and sharper spikes affecting a single unit are caused by defogging injections of 
	liquid nitrogen when a lid is opened and rapid chill injections when a lid is closed.
</p>

<p></p>

<p>
	Comments to s.kemp@cgiar.org.
</p>
INFO;

	$link = "<a href='javascript:contract()'>less info</a>";

	echo $info;
	echo $link;
?>